export const locationProfile = {
  postcode: "3136",
  suburb: "Croydon Hills",
  state: "VIC",
  preferredStores: [
    {
      id: "coles-croydon",
      name: "Coles Croydon",
      shortName: "Coles",
      address: "Croydon Central, Kent Ave, Croydon VIC 3136",
      distance: "nearby",
      sourceUrl: "https://www.croydoncentral.com.au/stores/coles",
    },
    {
      id: "coles-croydon-north",
      name: "Coles Croydon North",
      shortName: "Coles North",
      address: "Maroondah Hwy & Exeter Rd, Croydon North VIC 3136",
      distance: "nearby",
      sourceUrl: "https://www.coles.com.au/stores/storedetail/6706/storeDetail/630?brandId=2",
    },
    {
      id: "woolworths-croydon",
      name: "Woolworths Croydon",
      shortName: "Woolworths",
      address: "224-238 Mount Dandenong Rd, Croydon VIC 3136",
      distance: "nearby",
      sourceUrl: "https://www.woolworths.com.au/shop/storelocator/vic-croydon-3216",
    },
    {
      id: "aldi-croydon",
      name: "ALDI Croydon",
      shortName: "ALDI",
      address: "5-15 Kent Ave, Croydon VIC 3136",
      distance: "nearby",
      sourceUrl: "https://www.aldi.com.au/storelocator/l/croydon/15-5-kent-avenue/g378",
    },
    {
      id: "costco-ringwood",
      name: "Costco Ringwood",
      shortName: "Costco",
      address: "29 Bond St, Ringwood VIC 3134",
      distance: "short drive",
      sourceUrl: "https://www.costco.com.au/store-finder/Ringwood",
    },
    {
      id: "amazon-au",
      name: "Amazon AU",
      shortName: "Amazon AU",
      address: "Online delivery to 3136",
      distance: "online",
      sourceUrl: "https://www.amazon.com.au/s?k=grocery+snacks",
    },
    {
      id: "amazon-business",
      name: "Amazon Business AU",
      shortName: "Amazon Business",
      address: "Business-only pricing and quantity discounts",
      distance: "online",
      sourceUrl: "https://www.amazon.com.au/business",
    },
  ],
};

export const weekWindows = [
  {
    id: "current",
    label: "This week",
    range: "Wed 8 Jul - Tue 14 Jul",
    start: "2026-07-08",
    end: "2026-07-14",
    status: "Live catalogue",
  },
  {
    id: "next",
    label: "Next week",
    range: "Wed 15 Jul - Tue 21 Jul",
    start: "2026-07-15",
    end: "2026-07-21",
    status: "Future preview",
  },
  {
    id: "costco",
    label: "Costco",
    range: "Mon 6 Jul - Sun 2 Aug",
    start: "2026-07-06",
    end: "2026-08-02",
    status: "Warehouse booklet",
  },
];

export const sourceHealth = [
  {
    name: "Coles specials",
    cadence: "Wed-Tue",
    status: "Public catalogue",
    url: "https://www.coles.com.au/on-special?filter_Special=halfprice",
  },
  {
    name: "Woolworths specials",
    cadence: "Wed-Tue",
    status: "Public catalogue",
    url: "https://www.woolworths.com.au/shop/browse/specials",
  },
  {
    name: "ALDI catalogue",
    cadence: "Wed + Sat drops",
    status: "Needs store context",
    url: "https://www.catalogues.aldi.com.au/",
  },
  {
    name: "Costco Ringwood",
    cadence: "Monthly booklet",
    status: "Stock varies by warehouse",
    url: "https://www.costco.com.au/warehouse-savings",
  },
  {
    name: "Amazon AU",
    cadence: "Live marketplace",
    status: "Check seller, delivery and Subscribe & Save",
    url: "https://www.amazon.com.au/",
  },
  {
    name: "Amazon Business",
    cadence: "Live B2B pricing",
    status: "Check business-only and quantity discounts",
    url: "https://business.amazon.com.au/",
  },
  {
    name: "GCDB weekly cards",
    cadence: "Weekly",
    status: "Gift-card lead source",
    url: "https://gcdb.com.au/article/weekly-gift-card-offers/",
  },
  {
    name: "OzBargain gift cards",
    cadence: "Live community posts",
    status: "Verify expiry and caps",
    url: "https://www.ozbargain.com.au/tag/gift-card",
  },
];

export const products = [
  {
    id: "milo-original-bars-210",
    name: "Nestle MILO Original Snack Bars 10 Pack 210g",
    aliases: ["milo", "milo bars", "milo snack bars", "milo protein bars"],
    category: "Treats",
    unitLabel: "bar",
    watchTarget: 4.5,
    offers: [
      {
        retailer: "Coles Croydon",
        storeId: "coles-croydon",
        price: 9,
        unitPrice: 0.9,
        unitPrice100g: 4.29,
        tag: "Current shelf",
        weekId: "current",
        source: "Coles product page",
        confidence: "public product page",
        packNote: "10 x 21g",
        url: "https://www.coles.com.au/product/nestle-milo-original-snack-bars-10-pack-210g-2795815",
      },
      {
        retailer: "Woolworths Croydon",
        storeId: "woolworths-croydon",
        price: 9,
        unitPrice: 0.9,
        unitPrice100g: 4.29,
        tag: "Current shelf",
        weekId: "current",
        source: "Grocerize Woolworths lead",
        confidence: "comparison lead; verify in Woolworths",
        packNote: "10 x 21g",
        url: "https://www.woolworths.com.au/shop/search/products?searchTerm=milo%20snack%20bars",
      },
      {
        retailer: "Supermarket target",
        storeId: "coles-croydon",
        price: 4.5,
        unitPrice: 0.45,
        unitPrice100g: 2.14,
        tag: "Half-price target",
        weekId: "target",
        source: "Desired watch threshold",
        confidence: "not currently found",
        packNote: "10 x 21g",
        url: "https://www.grocerize.com.au/product/7789473136723/nestle-milo-original-snack-bars-10-pack-210g",
      },
      {
        retailer: "Costco Ringwood",
        storeId: "costco-ringwood",
        price: null,
        unitPrice: null,
        unitPrice100g: null,
        tag: "Bulk price check",
        weekId: "costco",
        source: "Costco official product page",
        confidence: "postcode/login needed",
        packNote: "30 x 27g",
        url: "https://www.costco.com.au/Business-Delivery/Nuts-Snacks-Confectionery/Chocolates/Nestle-MILO-Snack-Bars-30-x-27g/p/210426_BD",
      },
      {
        retailer: "Amazon AU",
        storeId: "amazon-au",
        price: null,
        unitPrice: null,
        unitPrice100g: null,
        tag: "Amazon price check",
        weekId: "current",
        source: "Amazon product/search page",
        confidence: "live price needed",
        packNote: "30 x 27g listing found",
        url: "https://www.amazon.com.au/Nestle-Milo-Snack-Bars-Gram/dp/B099Q53GV9",
      },
      {
        retailer: "Amazon Business",
        storeId: "amazon-business",
        price: null,
        unitPrice: null,
        unitPrice100g: null,
        tag: "Business quantity check",
        weekId: "current",
        source: "Amazon Business",
        confidence: "login needed for business-only price",
        packNote: "check quantity discounts",
        url: "https://business.amazon.com.au/",
      },
    ],
  },
  {
    id: "cadbury-dairy-milk-180",
    name: "Cadbury Dairy Milk Chocolate Block 180g",
    aliases: ["cadbury", "chocolate", "chocolate bar", "dairy milk", "block"],
    category: "Treats",
    unitLabel: "100g",
    watchTarget: 3.25,
    offers: [
      {
        retailer: "Woolworths Croydon",
        storeId: "woolworths-croydon",
        price: 5.5,
        unitPrice: 3.06,
        tag: "Current shelf",
        weekId: "current",
        source: "Public product/search lead",
        confidence: "needs live checkout",
        url: "https://www.woolworths.com.au/shop/productdetails/814479/cadbury-dairy-milk-chocolate-block",
      },
      {
        retailer: "Coles Croydon",
        storeId: "coles-croydon",
        price: 3.25,
        unitPrice: 1.81,
        tag: "Future half price",
        weekId: "next",
        source: "Indicative catalogue preview",
        confidence: "preview only",
        starts: "2026-07-15",
        url: "https://www.coles.com.au/on-special?filter_Special=halfprice",
      },
      {
        retailer: "IGA/Ritchies nearby",
        storeId: "other",
        price: 5.5,
        unitPrice: 3.06,
        tag: "Independent special",
        weekId: "current",
        source: "Local independent lead",
        confidence: "store dependent",
        url: "https://www.ritchies.com.au/",
      },
    ],
  },
  {
    id: "sensodyne-repair-protect",
    name: "Sensodyne Repair & Protect Toothpaste 100g",
    aliases: ["sensodyne", "toothpaste", "dental", "repair protect"],
    category: "Health",
    unitLabel: "100g",
    watchTarget: 5,
    offers: [
      {
        retailer: "Chemist Warehouse",
        storeId: "other",
        price: 5.99,
        unitPrice: 5.99,
        tag: "Pharmacy price",
        weekId: "current",
        source: "Alternative retailer lead",
        confidence: "check local stock",
        url: "https://www.chemistwarehouse.com.au/",
      },
      {
        retailer: "Coles Croydon",
        storeId: "coles-croydon",
        price: 6.5,
        unitPrice: 6.5,
        tag: "Half price",
        weekId: "current",
        source: "Coles half-price catalogue",
        confidence: "public catalogue",
        url: "https://www.coles.com.au/on-special?filter_Special=halfprice",
      },
      {
        retailer: "Woolworths Croydon",
        storeId: "woolworths-croydon",
        price: 7,
        unitPrice: 7,
        tag: "Special",
        weekId: "current",
        source: "Woolworths specials",
        confidence: "public catalogue",
        url: "https://www.woolworths.com.au/shop/browse/specials",
      },
    ],
  },
  {
    id: "head-shoulders-660",
    name: "Head & Shoulders Shampoo 660ml",
    aliases: ["head and shoulders", "head & shoulders", "shampoo", "hair"],
    category: "Household",
    unitLabel: "100ml",
    watchTarget: 1.4,
    offers: [
      {
        retailer: "Coles Croydon",
        storeId: "coles-croydon",
        price: 9.5,
        unitPrice: 1.44,
        tag: "Half price",
        weekId: "current",
        source: "Coles half-price catalogue",
        confidence: "public catalogue",
        url: "https://www.coles.com.au/on-special?filter_Special=halfprice",
      },
      {
        retailer: "Amazon AU",
        storeId: "other",
        price: 10.8,
        unitPrice: 1.64,
        tag: "Delivery option",
        weekId: "current",
        source: "Alternative retailer lead",
        confidence: "check seller and subscribe price",
        url: "https://www.amazon.com.au/",
      },
      {
        retailer: "Costco Ringwood",
        storeId: "costco-ringwood",
        price: 23.99,
        unitPrice: 1.21,
        tag: "Bulk buy",
        weekId: "costco",
        source: "Costco warehouse savings",
        confidence: "warehouse stock varies",
        packNote: "multi-pack equivalent",
        url: "https://www.costco.com.au/warehouse-savings",
      },
    ],
  },
  {
    id: "solo-10-pack",
    name: "Solo Lemon Soft Drink Cans 10 x 375ml",
    aliases: ["solo", "soft drink", "cans", "lemon"],
    category: "Drinks",
    unitLabel: "can",
    watchTarget: 0.75,
    offers: [
      {
        retailer: "Woolworths Croydon",
        storeId: "woolworths-croydon",
        price: 8.5,
        unitPrice: 0.85,
        tag: "Catalogue special",
        weekId: "current",
        source: "Woolworths catalogue",
        confidence: "public catalogue",
        url: "https://www.woolworths.com.au/shop/browse/specials",
      },
      {
        retailer: "Coles Croydon",
        storeId: "coles-croydon",
        price: 9,
        unitPrice: 0.9,
        tag: "Special",
        weekId: "current",
        source: "Coles specials",
        confidence: "public catalogue",
        url: "https://www.coles.com.au/on-special",
      },
      {
        retailer: "Costco Ringwood",
        storeId: "costco-ringwood",
        price: 24.99,
        unitPrice: 0.69,
        tag: "Bulk buy",
        weekId: "costco",
        source: "Costco warehouse savings",
        confidence: "warehouse stock varies",
        packNote: "36-can equivalent",
        url: "https://www.costco.com.au/warehouse-savings",
      },
    ],
  },
  {
    id: "dettol-wipes",
    name: "Dettol Antibacterial Wipes 120 pack",
    aliases: ["dettol", "wipes", "cleaning", "antibacterial"],
    category: "Cleaning",
    unitLabel: "wipe",
    watchTarget: 0.05,
    offers: [
      {
        retailer: "Woolworths Croydon",
        storeId: "woolworths-croydon",
        price: 4.5,
        unitPrice: 0.038,
        tag: "Half price",
        weekId: "current",
        source: "Woolworths specials",
        confidence: "public catalogue",
        url: "https://www.woolworths.com.au/shop/browse/specials",
      },
      {
        retailer: "Coles Croydon",
        storeId: "coles-croydon",
        price: 5,
        unitPrice: 0.042,
        tag: "Special",
        weekId: "current",
        source: "Coles specials",
        confidence: "public catalogue",
        url: "https://www.coles.com.au/on-special",
      },
      {
        retailer: "The Reject Shop",
        storeId: "other",
        price: 4,
        unitPrice: 0.033,
        tag: "Alternative store",
        weekId: "current",
        source: "Alternative retailer lead",
        confidence: "check local stock",
        url: "https://www.rejectshop.com.au/",
      },
    ],
  },
  {
    id: "musashi-protein-bar-90",
    name: "Musashi High Protein Bar 90g",
    aliases: ["musashi", "protein bar", "high protein", "bar"],
    category: "Fitness",
    unitLabel: "bar",
    watchTarget: 3.45,
    offers: [
      {
        retailer: "Woolworths Croydon",
        storeId: "woolworths-croydon",
        price: 3.45,
        unitPrice: 3.45,
        tag: "Half price",
        weekId: "current",
        source: "Previously verified live Woolworths offer",
        confidence: "recheck before checkout",
        url: "https://www.woolworths.com.au/",
      },
      {
        retailer: "Coles Croydon",
        storeId: "coles-croydon",
        price: 6.9,
        unitPrice: 6.9,
        tag: "Regular shelf",
        weekId: "current",
        source: "Prior retail watch anchor",
        confidence: "recheck live page",
        url: "https://www.coles.com.au/",
      },
      {
        retailer: "Chemist Warehouse",
        storeId: "other",
        price: 4.5,
        unitPrice: 4.5,
        tag: "4-pack effective",
        weekId: "current",
        source: "Prior retail watch anchor",
        confidence: "location dependent",
        url: "https://www.chemistwarehouse.com.au/",
      },
    ],
  },
];

export const bulkDecisionCases = [
  {
    id: "milo-original-bars-210",
    title: "Bulk vs half-price decision",
    productName: "Nestle MILO Original Snack Bars",
    productId: "milo-original-bars-210",
    note: "For this product, do not assume Costco is cheaper. Compare both by bar count and by grams because Costco bars are larger.",
    sameBarsNowLimit: 27,
    sameBarsHalfLimit: 13.5,
    sameGramsNowLimit: 34.71,
    sameGramsHalfLimit: 17.36,
    halfPriceFrequency: "Rare recently; keep it on watch instead of assuming a sale is coming next week.",
    rows: [
      {
        retailer: "Coles",
        pack: "10 bars",
        grams: 210,
        price: 9,
        priceBasis: "$9.00 / 10",
        source: "Coles product page",
        sourceUrl: "https://www.coles.com.au/product/nestle-milo-original-snack-bars-10-pack-210g-2795815",
        status: "Buy only if urgent",
      },
      {
        retailer: "Woolworths",
        pack: "10 bars",
        grams: 210,
        price: 9,
        priceBasis: "$9.00 / 10",
        source: "Grocerize lead; verify Woolworths checkout",
        sourceUrl: "https://www.grocerize.com.au/product/7789473136723/nestle-milo-original-snack-bars-10-pack-210g",
        status: "Buy only if urgent",
      },
      {
        retailer: "Supermarket half-price target",
        pack: "10 bars",
        grams: 210,
        price: 4.5,
        priceBasis: "$4.50 / 10",
        source: "Watch threshold",
        sourceUrl: "https://www.grocerize.com.au/product/7789473136723/nestle-milo-original-snack-bars-10-pack-210g",
        status: "Best price if it appears",
      },
      {
        retailer: "Costco Ringwood",
        pack: "30 bars",
        grams: 810,
        price: null,
        priceBasis: "Needs 3136 postcode/login",
        source: "Costco official product page",
        sourceUrl: "https://www.costco.com.au/Business-Delivery/Nuts-Snacks-Confectionery/Chocolates/Nestle-MILO-Snack-Bars-30-x-27g/p/210426_BD",
        status: "Check official price",
      },
      {
        retailer: "DoorDash / Costco proxy",
        pack: "30 bars",
        grams: 810,
        price: 27.29,
        priceBasis: "Delivery proxy",
        source: "DoorDash local price lead",
        sourceUrl: "https://www.doordash.com/products/nestl-milo-snack-bars-27-g-x-30-ct/ugp_91b2e126-f100-45d5-bad5-54ff37ba34ff",
        status: "Beats current by grams, not half-price",
      },
      {
        retailer: "Amazon AU",
        pack: "30 bars",
        grams: 810,
        price: null,
        priceBasis: "Live price check",
        source: "Amazon AU listing",
        sourceUrl: "https://www.amazon.com.au/Nestle-Milo-Snack-Bars-Gram/dp/B099Q53GV9",
        status: "Compare before checkout",
      },
      {
        retailer: "Amazon Business",
        pack: "varies",
        grams: null,
        price: null,
        priceBasis: "Business price + quantity discount",
        source: "Amazon Business AU",
        sourceUrl: "https://business.amazon.com.au/",
        status: "Check business-only deals",
      },
      {
        retailer: "ALDI alternative",
        pack: "protein oat bars",
        grams: 200,
        price: 4.49,
        priceBasis: "$4.49 / 5",
        source: "ALDI-style alternative to validate weekly",
        sourceUrl: "https://www.catalogues.aldi.com.au/",
        status: "Not same product; compare health",
      },
    ],
  },
];

export const healthProfiles = {
  "milo-original-bars-210": {
    verdict: "Treat, not a real protein snack",
    summary:
      "It is fine occasionally, but low protein means it may not keep you full. Bulk buying a craving food can make self-control harder.",
    metrics: [
      { label: "Energy", value: "300 kJ", tone: "neutral", note: "per 21g bar" },
      { label: "Protein", value: "1.1g", tone: "warn", note: "low satiety" },
      { label: "Sugar", value: "3.9g", tone: "watch", note: "moderate per small bar" },
      { label: "Fibre", value: "2.2g", tone: "good", note: "helpful" },
      { label: "Recall", value: "Check batch", tone: "watch", note: "Feb 2026 recall for select Aug 2026 batches" },
    ],
    recommendation:
      "If you buy it, buy the smallest pack or set a hard weekly limit. Do not bulk buy unless the price is excellent and you can portion it.",
  },
};

export const cravingSwaps = [
  {
    name: "Greek yoghurt + cocoa",
    why: "Creamy and chocolatey with better protein.",
    protein: "15-20g",
    sugar: "5-8g",
    habit: "Use a sweetener or berries if needed.",
  },
  {
    name: "Frozen grapes",
    why: "Sweet, cold and slow to eat.",
    protein: "0g",
    sugar: "natural",
    habit: "Portion into a bowl, not the full bag.",
  },
  {
    name: "Protein yoghurt bar",
    why: "Still feels like dessert but fills better.",
    protein: "8-12g",
    sugar: "varies",
    habit: "Compare per bar; avoid buying boxes you will finish fast.",
  },
  {
    name: "Apple + peanut butter + choc chips",
    why: "Crunch, sweetness and chocolate hit in one snack.",
    protein: "4-6g",
    sugar: "moderate",
    habit: "Measure peanut butter and choc chips first.",
  },
];

export const giftCardDeals = [
  {
    id: "restaurant-uber-coles",
    title: "10% off Restaurant Choice / Uber",
    retailer: "Coles",
    source: "GCDB weekly offer",
    window: "Wed 8 Jul - Tue 14 Jul",
    effectiveDiscount: 10,
    groceryUsable: false,
    bestFor: "Takeaway, rides, restaurant nights",
    caveat: "Useful for eating out, not grocery checkout.",
    url: "https://gcdb.com.au/article/weekly-gift-card-offers/",
  },
  {
    id: "tcn-woolworths",
    title: "20x Everyday Rewards on selected TCN cards",
    retailer: "Woolworths",
    source: "GCDB weekly offer",
    window: "Wed 8 Jul - Tue 14 Jul",
    effectiveDiscount: 10,
    groceryUsable: false,
    bestFor: "JB Hi-Fi, Rebel, Supercheap or included TCN partners",
    caveat: "Points value assumes 2000 Everyday Rewards points = $10.",
    url: "https://gcdb.com.au/article/weekly-gift-card-offers/",
  },
  {
    id: "ozbargain-watch",
    title: "Live gift-card deal watch",
    retailer: "OzBargain",
    source: "Community deal feed",
    window: "Live",
    effectiveDiscount: null,
    groceryUsable: "varies",
    bestFor: "Catch one-off Woolworths, Coles, WISH, Apple or Amazon deals",
    caveat: "Always verify caps, expiry, targeted terms and payment method.",
    url: "https://www.ozbargain.com.au/tag/gift-card",
  },
];

export const quickListSeeds = [
  "Nestle MILO Original Snack Bars 10 Pack 210g",
  "Cadbury Dairy Milk Chocolate Block 180g",
  "Sensodyne Repair & Protect Toothpaste 100g",
  "Solo Lemon Soft Drink Cans 10 x 375ml",
];

export const accountConnections = [
  {
    id: "coles",
    name: "Coles",
    purpose: "Order history, receipts, Flybuys-linked offers and current trolley prices.",
    loginUrl: "https://www.coles.com.au/login",
    status: "Manual login needed",
    historyAccess: "Good after login",
  },
  {
    id: "woolworths",
    name: "Woolworths",
    purpose: "Past orders, Everyday Rewards-linked offers and store-specific availability.",
    loginUrl: "https://www.woolworths.com.au/shop/securelogin",
    status: "Manual login needed",
    historyAccess: "Good after login",
  },
  {
    id: "costco",
    name: "Costco",
    purpose: "Member-only prices, warehouse availability and bulk-buy checks.",
    loginUrl: "https://www.costco.com.au/login",
    status: "Membership login needed",
    historyAccess: "Limited to online/member-visible purchase records",
  },
  {
    id: "amazon",
    name: "Amazon AU",
    purpose: "Order history, live marketplace price and Subscribe & Save checks.",
    loginUrl: "https://www.amazon.com.au/gp/css/order-history",
    status: "Manual login needed",
    historyAccess: "Good after login",
  },
  {
    id: "amazon-business",
    name: "Amazon Business",
    purpose: "Business-only pricing, quantity discounts and invoices.",
    loginUrl: "https://business.amazon.com.au/",
    status: "Business login needed",
    historyAccess: "Good after login",
  },
  {
    id: "aldi",
    name: "ALDI",
    purpose: "Catalogue and Special Buys checks; receipt import for store purchases.",
    loginUrl: "https://www.aldi.com.au/",
    status: "Catalogue plus manual receipts",
    historyAccess: "No standard grocery account history",
  },
];

export const livePriceAudits = {
  "milo-original-bars-210": {
    checkedAt: "9 Jul 2026",
    location: "Croydon Hills 3136",
    productName: "Nestle MILO Original Snack Bars 10 Pack 210g",
    recommendation: "Wait or buy one small pack only if urgent",
    recommendationDetail:
      "The cheapest confirmed exact product today is $9.00 at Coles/Woolworths. A good buy is $4.50 or less. Costco, Amazon and Amazon Business need live account/postcode checks before they can beat that.",
    goodBuyPrice: 4.5,
    futureSignal:
      "No confirmed future catalogue price found for this exact MILO bar today. Put it on watch for Wednesday catalogue changes.",
    historySignal:
      "Recent public comparison shows Coles/Woolworths at $9.00. CamelCamelCamel has an Amazon AU history page for the 30-pack listing, but Amazon currently shows that listing as unavailable in the public page.",
    rows: [
      {
        retailer: "Coles",
        match: "Exact product",
        pack: "10 x 21g",
        grams: 210,
        price: 9,
        unit: "$0.90 / bar",
        per100g: "$4.29 / 100g",
        confidence: "Verified from Coles product page",
        action: "Buy only if urgent",
        url: "https://www.coles.com.au/product/nestle-milo-original-snack-bars-10-pack-210g-2795815",
      },
      {
        retailer: "Woolworths",
        match: "Exact product",
        pack: "10 x 21g",
        grams: 210,
        price: 9,
        unit: "$0.90 / bar",
        per100g: "$4.29 / 100g",
        confidence: "Grocerize lead; verify Woolworths checkout after login",
        action: "Buy only if urgent",
        url: "https://www.grocerize.com.au/product/7789473136723/nestle-milo-original-snack-bars-10-pack-210g",
      },
      {
        retailer: "ALDI",
        match: "No exact match found",
        pack: "N/A",
        grams: null,
        price: null,
        unit: "N/A",
        per100g: "N/A",
        confidence: "Catalogue/source check only",
        action: "Use as alternative snack source, not exact comparison",
        url: "https://www.catalogues.aldi.com.au/",
      },
      {
        retailer: "Costco Ringwood",
        match: "Bulk version",
        pack: "30 x 27g",
        grams: 810,
        price: null,
        unit: "Needs member price",
        per100g: "Needs member price",
        confidence: "Official product exists; price requires postcode/member session",
        action: "Connect Costco, then compare",
        url: "https://www.costco.com.au/Business-Delivery/Nuts-Snacks-Confectionery/Chocolates/Nestle-MILO-Snack-Bars-30-x-27g/p/210426_BD",
      },
      {
        retailer: "Amazon AU",
        match: "30-pack listing",
        pack: "30 x 27g",
        grams: 810,
        price: null,
        unit: "Unavailable publicly",
        per100g: "Unavailable publicly",
        confidence: "Amazon public page currently shows unavailable",
        action: "Check CamelCamelCamel and live Amazon",
        url: "https://www.amazon.com.au/Nestle-Milo-Snack-Bars-Gram/dp/B099Q53GV9",
      },
      {
        retailer: "Amazon Business",
        match: "Business quantity source",
        pack: "Varies",
        grams: null,
        price: null,
        unit: "Needs business login",
        per100g: "Needs business login",
        confidence: "Business-only price not public",
        action: "Connect Amazon Business",
        url: "https://business.amazon.com.au/",
      },
    ],
    thresholds: [
      {
        label: "Best confirmed today",
        value: "$9.00",
        note: "Coles/Woolworths exact product",
      },
      {
        label: "Good buy target",
        value: "$4.50",
        note: "True half-price target",
      },
      {
        label: "Costco beats current",
        value: "< $27.00",
        note: "By bar count for 30 bars",
      },
      {
        label: "Costco beats half-price",
        value: "< $13.50",
        note: "By bar count for 30 bars",
      },
    ],
    historyLinks: [
      {
        label: "Amazon history",
        source: "CamelCamelCamel AU",
        status: "History page available; current Amazon listing unavailable publicly",
        url: "https://au.camelcamelcamel.com/product/B099Q53GV9",
      },
      {
        label: "Supermarket comparison",
        source: "Grocerize",
        status: "Shows Coles and Woolworths at $9.00 today",
        url: "https://www.grocerize.com.au/product/7789473136723/nestle-milo-original-snack-bars-10-pack-210g",
      },
    ],
  },
};
